/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Copyright (C) 2024 Ventana Micro Systems Ltd.
 */

#ifndef _ASM_RISCV_RPMI_H
#define _ASM_RISCV_RPMI_H

#define RPMI_MAJOR_VER		(0x0000)
#define RPMI_MINOR_VER		(0x0001)
#define RPMI_MSGPROTO_VERSION(Major, Minor) ((Major << 16) | Minor)

/**
 * RPMI Error Codes
 */
enum rpmi_error_codes {
	RPMI_SUCCESS = 0,
	RPMI_ERROR_FAILED = -1,
	RPMI_ERROR_NOT_SUPPORTED = -2,
	RPMI_ERROR_INVALID_PARAM = -3,
	RPMI_ERROR_DENIED = -4,
	RPMI_ERROR_NOT_FOUND = -5,
	RPMI_ERROR_OUT_OF_RANGE = -6,
	RPMI_ERROR_OUT_OF_RESOURCE = -7,
	RPMI_ERROR_HW_FAULT = -8,
	RPMI_ERROR_BUSY = -9,
	RPMI_ERROR_TIMEOUT = -10,
	RPMI_ERROR_COMMS = -11,
	RPMI_ERROR_ALREADY = -12,
	RPMI_ERROR_EXTENSION = -13,
};

#define RPMI_SRVGRP_CLOCK	0x00007

/* RPMI Clock Service IDs */
enum rpmi_clock_service_id {
	RPMI_CLK_SRV_ENABLE_NOTIFICATION = 0x01,
	RPMI_CLK_SRV_GET_SYSTEM_CLOCKS = 0x02,
	RPMI_CLK_SRV_GET_ATTRIBUTES = 0x03,
	RPMI_CLK_SRV_GET_SUPPORTED_RATES = 0x04,
	RPMI_CLK_SRV_SET_CONFIG = 0x05,
	RPMI_CLK_SRV_GET_CONFIG = 0x06,
	RPMI_CLK_SRV_SET_RATE = 0x07,
	RPMI_CLK_SRV_GET_RATE = 0x08,
	RPMI_CLK_SRV_ID_MAX_COUNT,
};

#endif /* _ASM_RISCV_RPMI_H */
